Algoritmo "EXER12"

Var A, B, Adi, sub, divi, mult:real

Inicio
    Escreva("Primeiro número: ")
    Leia(A)
    Escreva("Segundo número: ")
    Leia(B)
    Adi<-(A+B)
    Sub<-(A-B)
    divi<-(A/B)
    mult<-(A*B)
    Escreva("Resultado da adição =", Adi)
    Escreva(" Resultado da subtração =", Sub)
    Escreva(" Resultado da divisão =", divi)
    Escreva(" Resultado da multiplicação =", mult)
    
Fimalgoritmo